services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_backend
    ports:
      - "4000:4000"
    environment:
      - ENV=Docker
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest 
    ports:
      - "27017:27017"
  
  frontend:
    build:
      context: .
      dockerfile: Dockerfile_frontend
    
    image: sjingoi/quirknotes_frontend:latest
    ports:
      - "3000:80"
    environment:
      - ENV=Docker